DATA_SERVICE_NAME = "DATA_SERVICE"
INDEX_DATA_STREAM_NAME = "INDEX_DATA_STREAM"
MARKET_DATA_STREAM_NAME = "MARKET_DATA_STREAM"
FOREIGN_DATA_STREAM_NAME = "FOREIGN_DATA_STREAM"
BAR_DATA_STREAM_NAME = "BAR_DATA_STREAM"

